name: Feature Request
description: Use this template to submit an idea for an enhancement to the game. Please use the [blank issue form](https://github.com/beyond-all-reason/Beyond-All-Reason/issues/new) if your issue is not specifically a feature request.
labels: ["Enhancement"]

body:
  - type: textarea
    attributes:
      label: Description
      description: Brief description of the feature
    validations:
      required: true

  - type: textarea
    attributes:
      label: Problems this will solve
      description: Explain the issues this feature would solve, or how it may impact the game
    validations:
      required: true

  - type: dropdown
    id: feature_type
    attributes:
      label: What area of the game does this feature request pertain?
      description: Issues with the gameplay box checked will be discussed by the Game Design Team
      multiple: true
      options:
        - 'Gameplay'
        - 'Graphics'
        - 'UI/UX'
        - 'Settings, Controls or Hotkeys'
        - 'Codebase or APIs'
        - 'Other'
    validations:
      required: true

  - type: textarea
    attributes:
      label: Other (optional)
      description: Optionally, you can provide implementation notes for developers, further ways this feature could be enhanced, potential issues this feature could introduce and how those problems could be mitigated, alternative solutions, or anything else you wish to add here
