name: Translations rebase from master

on:
  workflow_dispatch: 
  schedule:
  - cron: '15 5 * * 1'

permissions: write-all

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Git User
        run: |
          git config user.name "GitHub Action"

      - name: Transifex Rebase
        run: |
          git checkout transifex-test
          git fetch origin
          git checkout transifex-synchronization-source
          git pull
          git rebase origin/transifex-test
          git push origin transifex-synchronization-source
